### ISSUE TITLE
Server is compromised

### ISSUE THREAD

**Issue by nikolowry** [Max00355/HNLive#4]
Not the most appropriate place (didn't see you on twitter) - but http://hnlive.cf got hijacked and is now redirecting to http://resumereviewers.com/. 

From snooping around, it looks like you might have just mixed up some DNS configs and that resumereviewers is another one of your projects (the payment modal has your name, "Frankie Primerano
", in the header).

If resumereviewers is not yours and your server runs apache, then I'd assume it might be a simple htaccess hack.

**Comment by f-prime** [comment]
Nope, not hijacked, that was me. Haha

**Comment by nikolowry** [comment]
Well it was hijacked - you were just the culprit and the victim! Ha.

I've been leaving it up all day as a pinned tab, hope to see it back tomorrow!  Thanks

**Comment by f-prime** [comment]
Give me 15 minutes :P

**Comment by f-prime** [comment]
I have updated the DNS, give it a bit of time.
